version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@NBGames2000'
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn next_board_games.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://usuario_do_banco_de_dados:senha_do_banco_de_dados@db/nome_do_banco_de_dados

volumes:
  postgres_data: