# Generated by Django 5.0.3 on 2024-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_board_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_data', models.BinaryField()),
            ],
        ),
    ]
