# Generated by Django 5.0.3 on 2024-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_board_games', '0002_trainedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_data', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
