# Generated by Django 5.0.3 on 2024-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_board_games', '0003_modelstorage_jogo_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='ano_nacional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='artistas',
            field=models.ManyToManyField(blank=True, related_name='artistas', to='next_board_games.profissional'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='next_board_games.categoria'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='designers', to='next_board_games.profissional'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='idade_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='mecanicas',
            field=models.ManyToManyField(blank=True, to='next_board_games.mecanica'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_favorito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_jogadores_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_jogadores_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_jogou',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_quer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_tem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='qt_teve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='temas',
            field=models.ManyToManyField(blank=True, to='next_board_games.tema'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='thumb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='tp_jogo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='vl_tempo_jogo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
